import { z } from "zod";
import { eq } from "drizzle-orm";
import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { adminProcedure, protectedProcedure, publicProcedure, router } from "./_core/trpc";
import { createAuditLog, getDb, listCategories, listEntries, listStatements, listStatementTransactions, listTags } from "./db";
import { categories, entries, entryTags, tags, statements } from "../drizzle/schema";
import { storagePut } from "./storage";

export const appRouter = router({
  system: systemRouter,
  auth: router({
    me: publicProcedure.query(opts => opts.ctx.user),
    logout: publicProcedure.mutation(({ ctx }) => { const cookieOptions = getSessionCookieOptions(ctx.req); ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 }); return { success: true } as const; }),
  }),
  finance: router({
    dashboard: protectedProcedure.query(async () => listEntries()),
    entries: protectedProcedure.query(async () => listEntries()),
    categories: protectedProcedure.query(async () => listCategories()),
    tags: protectedProcedure.query(async () => listTags()),
    statements: protectedProcedure.query(async () => listStatements()),
    statementTransactions: protectedProcedure.input(z.object({ statementId: z.number().optional() }).optional()).query(async ({ input }) => listStatementTransactions(input?.statementId)),
    createEntry: protectedProcedure.input(z.object({ type: z.enum(["income", "expense"]), amount: z.number().positive(), occurredAt: z.coerce.date(), description: z.string().min(2), notes: z.string().optional(), categoryId: z.number().optional(), tagIds: z.array(z.number()).default([]), status: z.enum(["pending", "classified", "divergence", "reconciled"]).default("classified") })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Banco de dados indisponível"); const inserted = await db.insert(entries).values({ type: input.type, amount: input.amount.toFixed(2), occurredAt: input.occurredAt, description: input.description, notes: input.notes, categoryId: input.categoryId, status: input.status, createdBy: ctx.user.id, updatedBy: ctx.user.id, originalDescription: input.description, originalType: input.type }).$returningId(); const id = inserted[0]?.id; if (id && input.tagIds.length) await db.insert(entryTags).values(input.tagIds.map(tagId => ({ entryId: id, tagId }))); await createAuditLog({ actorId: ctx.user.id, actorName: ctx.user.name ?? undefined, action: "create", entityType: "financial_entry", entityId: id, details: JSON.stringify(input) }); return { id }; }),
    createCategory: protectedProcedure.input(z.object({ name: z.string().min(2), description: z.string().optional(), kind: z.enum(["income", "expense", "both"]).default("both") })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Banco de dados indisponível"); const inserted = await db.insert(categories).values({ ...input, createdBy: ctx.user.id }).$returningId(); await createAuditLog({ actorId: ctx.user.id, actorName: ctx.user.name ?? undefined, action: "create", entityType: "category", entityId: inserted[0]?.id, details: input.name }); return inserted[0]; }),
    updateEntry: protectedProcedure.input(z.object({ id: z.number(), type: z.enum(["income", "expense"]).optional(), amount: z.number().positive().optional(), occurredAt: z.coerce.date().optional(), description: z.string().min(2).optional(), notes: z.string().optional(), categoryId: z.number().optional(), status: z.enum(["pending", "classified", "divergence", "reconciled", "excluded"]).optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Banco de dados indisponível"); const { id, amount, ...rest } = input; await db.update(entries).set({ ...rest, ...(amount !== undefined ? { amount: amount.toFixed(2) } : {}), updatedBy: ctx.user.id }).where(eq(entries.id, id)); await createAuditLog({ actorId: ctx.user.id, actorName: ctx.user.name ?? undefined, action: "update", entityType: "financial_entry", entityId: id, details: JSON.stringify(input) }); return { success: true }; }),
    deleteEntry: protectedProcedure.input(z.object({ id: z.number() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Banco de dados indisponível"); await db.update(entries).set({ status: "excluded", updatedBy: ctx.user.id }).where(eq(entries.id, input.id)); await createAuditLog({ actorId: ctx.user.id, actorName: ctx.user.name ?? undefined, action: "delete", entityType: "financial_entry", entityId: input.id, details: "Exclusão lógica confirmada pelo usuário" }); return { success: true }; }),
    reconcileEntry: protectedProcedure.input(z.object({ id: z.number(), status: z.enum(["classified", "divergence", "reconciled"]), statementId: z.number().optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Banco de dados indisponível"); await db.update(entries).set({ status: input.status, ...(input.statementId ? { statementId: input.statementId } : {}), updatedBy: ctx.user.id }).where(eq(entries.id, input.id)); await createAuditLog({ actorId: ctx.user.id, actorName: ctx.user.name ?? undefined, action: "reconcile", entityType: "financial_entry", entityId: input.id, details: JSON.stringify({ status: input.status, statementId: input.statementId }) }); return { success: true }; }),
    createStatement: protectedProcedure.input(z.object({ fileName: z.string().min(1), base64Data: z.string().min(1), mimeType: z.literal("application/pdf") })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Banco de dados indisponível"); const buffer = Buffer.from(input.base64Data, "base64"); const stored = await storagePut(`statements/${ctx.user.id}/${Date.now()}-${input.fileName}`, buffer, input.mimeType); const result = await db.insert(statements).values({ fileName: input.fileName, fileKey: stored.key, fileUrl: stored.url, importedBy: ctx.user.id, status: "pending" }).$returningId(); await createAuditLog({ actorId: ctx.user.id, actorName: ctx.user.name ?? undefined, action: "import", entityType: "bank_statement", entityId: result[0]?.id, details: input.fileName }); return { id: result[0]?.id, url: stored.url }; }),
    createStatementTransaction: protectedProcedure.input(z.object({ statementId: z.number(), type: z.enum(["income", "expense"]), amount: z.number().positive(), occurredAt: z.coerce.date(), description: z.string().min(2) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Banco de dados indisponível"); const { statementTransactions } = await import("../drizzle/schema"); const inserted = await db.insert(statementTransactions).values({ statementId: input.statementId, type: input.type, amount: input.amount.toFixed(2), occurredAt: input.occurredAt, description: input.description, status: "pending" }).$returningId(); const statementRows = await db.select().from(statementTransactions).where(eq(statementTransactions.statementId, input.statementId)); await db.update(statements).set({ movementCount: statementRows.length, pendingCount: statementRows.filter(row => row.status === "pending").length, status: "pending" }).where(eq(statements.id, input.statementId)); await createAuditLog({ actorId: ctx.user.id, actorName: ctx.user.name ?? undefined, action: "create", entityType: "statement_transaction", entityId: inserted[0]?.id, details: JSON.stringify(input) }); return { id: inserted[0]?.id }; }),
    matchStatementTransaction: protectedProcedure.input(z.object({ transactionId: z.number(), entryId: z.number().optional(), status: z.enum(["matched", "divergence", "pending"]) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Banco de dados indisponível"); const { statementTransactions } = await import("../drizzle/schema"); const existing = await db.select().from(statementTransactions).where(eq(statementTransactions.id, input.transactionId)).limit(1); const statementId = existing[0]?.statementId; await db.update(statementTransactions).set({ matchedEntryId: input.status === "pending" ? null : input.entryId ?? null, status: input.status }).where(eq(statementTransactions.id, input.transactionId)); if (input.entryId && input.status !== "pending") await db.update(entries).set({ status: input.status === "matched" ? "reconciled" : "divergence", updatedBy: ctx.user.id }).where(eq(entries.id, input.entryId)); if (statementId) { const statementRows = await db.select().from(statementTransactions).where(eq(statementTransactions.statementId, statementId)); const pendingCount = statementRows.filter(row => row.status === "pending").length; await db.update(statements).set({ movementCount: statementRows.length, pendingCount, status: pendingCount === 0 ? "reconciled" : "pending" }).where(eq(statements.id, statementId)); } await createAuditLog({ actorId: ctx.user.id, actorName: ctx.user.name ?? undefined, action: "match", entityType: "statement_transaction", entityId: input.transactionId, details: JSON.stringify(input) }); return { success: true }; }),
    createTag: protectedProcedure.input(z.object({ name: z.string().min(2), description: z.string().optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Banco de dados indisponível"); const inserted = await db.insert(tags).values({ ...input, createdBy: ctx.user.id }).$returningId(); await createAuditLog({ actorId: ctx.user.id, actorName: ctx.user.name ?? undefined, action: "create", entityType: "tag", entityId: inserted[0]?.id, details: input.name }); return inserted[0]; }),
    audit: adminProcedure.query(async () => { const db = await getDb(); if (!db) return []; const { auditLogs } = await import("../drizzle/schema"); return db.select().from(auditLogs); }),
  }),
});

export type AppRouter = typeof appRouter;
